### ISSUE TITLE
Using GCP Pub/Sub instead of RabbitMQ

### ISSUE THREAD

**Issue by qdelamea** [dotnet-architecture/eShopOnDapr#102]
HI everyone,

I'm trying to deploy eShopOnDapr on GCP using GCP's native services. I decided to it step by step and I started by running the project locally replacing the RabbitMQ broker with GCP Pub/Sub. To do so, I removed the RabbitMQ service from the docker-compose manifest files and I changed the Dapr pubsub component manifest file.

On GCP, I Just created a service account and I rewrite the pubsub component as follows.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: eshop
spec:
  type: pubsub.gcp.pubsub
  version: v1
  metadata:
  - name: type
    value: service_account
  - name: projectId
    value: eshopondapr-gke
  - name: privateKeyId
    value: d963d1894729920ad4a215e5bae2c21cd21a6501
  - name: clientEmail
    value: test-topic@eshopondapr-gke.iam.gserviceaccount.com
  - name: clientId
    value: 111813814908509833397
  - name: authUri
    value: https://accounts.google.com/o/oauth2/auth
  - name: tokenUri
    value: https://oauth2.googleapis.com/token
  - name: authProviderX509CertUrl
    value: https://www.googleapis.com/oauth2/v1/certs
  - name: clientX509CertUrl
    value: https://www.googleapis.com/robot/v1/metadata/x509/test-topic%40eshopondapr-gke.iam.gserviceaccount.com
  - name: privateKey
    value: "-----BEGIN PRIVATE KEY-----...."

```

I have first tested the GCP component with this example https://github.com/dapr/js-sdk/tree/master/examples/http/pubsub and it worked. However, with eShopOnDapr it doesn't work and Dapr containers crash. Here are the logs of the catalog-api-dapr container.

```
time="2022-07-13T14:12:27.4985375Z" level=info msg="starting Dapr Runtime -- version 1.7.2 -- commit 1f8c0abfc73bb14a71435519e56b2aecb4385f01" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:27.4986179Z" level=info msg="log level set to: info" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:27.498748Z" level=info msg="metrics server started on :9090/" app_id=webshoppingagg instance=80c979110637 scope=dapr.metrics type=log ver=1.7.2
time="2022-07-13T14:12:27.5000501Z" level=info msg="standalone mode configured" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:27.5001167Z" level=info msg="app id: webshoppingagg" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:27.5007754Z" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:27.5015583Z" level=info msg="local service entry announced: webshoppingagg -> 172.19.0.16:33231" app_id=webshoppingagg instance=80c979110637 scope=dapr.contrib type=log ver=1.7.2
time="2022-07-13T14:12:27.5017078Z" level=info msg="Initialized name resolution to mdns" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:27.5021811Z" level=info msg="loading components" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:27.505091Z" level=info msg="rabbitmq pub/sub: connectionCount: current=0 reference=0" app_id=webshoppingagg instance=80c979110637 scope=dapr.contrib type=log ver=1.7.2
time="2022-07-13T14:12:32.5057019Z" level=warning msg="process component error daprd process will exited, gracefully to stop" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:32.5057772Z" level=info msg="dapr shutting down." app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:32.5057939Z" level=info msg="Stopping Dapr APIs" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:32.505839Z" level=info msg="Waiting 5s to finish outstanding operations" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:37.5061596Z" level=info msg="Shutting down all components" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2
time="2022-07-13T14:12:37.5062717Z" level=fatal msg="process component pubsub error: init timeout for component pubsub exceeded after 5s" app_id=webshoppingagg instance=80c979110637 scope=dapr.runtime type=log ver=1.7.2

```

I don't understand why there is a reference to RabbitMQ as the component doesn't exist anymore. Moreover, I don't understand why the component doesn't work as it should!

Can anyone help me?

Thanks,

Quentin
